android.useAndroidX=true
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=37
android.aapt2FromMavenOverride=/data/user/0/com.iqge/files/usr/bin/aapt2
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx1536m
org.gradle.parallel=false
org.gradle.caching=true
