package com.zhizhu.zhicode;

import android.graphics.Color;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.Space;
import android.widget.TextView;
import android.content.Context;
import org.json.JSONArray;
import org.json.JSONObject;

/** Safe scene-graph adapter. Existing behavior stays in named slots; custom nodes are presentation-only. */
public final class UiCanvasController {
    public static final int MAX_OPS=80;
    private UiCanvasController(){}
    public static void apply(View root,JSONObject document){if(root==null||document==null)return;JSONArray nodes=document.optJSONArray("nodes");if(nodes==null){JSONObject s=document.optJSONObject("screens");JSONObject c=s==null?null:s.optJSONObject("chat");nodes=c==null?null:c.optJSONArray("nodes");}if(nodes==null||nodes.length()>400)return;for(int i=0;i<nodes.length();i++){JSONObject n=nodes.optJSONObject(i);if(n!=null)applyNode(root,n);}}
    private static void applyNode(View root,JSONObject n){String id=n.optString("id","");if(!safeId(id))return;View v=find(root,id);if(n.optBoolean("removed",false)){if(v!=null&&v.getTag()!=null&&!id.endsWith(".root"))v.setVisibility(View.GONE);return;}if(v==null&&n.has("parent"))v=createNode(root,n);if(v==null)return;if(n.has("parent")){View parent=find(root,n.optString("parent",""));if(parent instanceof ViewGroup&&v.getParent()!=parent){if(v.getParent() instanceof ViewGroup)((ViewGroup)v.getParent()).removeView(v);((ViewGroup)parent).addView(v);}}if(v.getParent() instanceof ViewGroup&&n.has("index")){ViewGroup g=(ViewGroup)v.getParent();int target=Math.max(0,Math.min(g.getChildCount()-1,n.optInt("index",g.indexOfChild(v))));int current=g.indexOfChild(v);if(current>=0&&target!=current){g.removeViewAt(current);g.addView(v,target);}}applyProperties(v,n);}
    private static View createNode(View root,JSONObject n){View parent=find(root,n.optString("parent",""));if(!(parent instanceof ViewGroup))return null;Context c=root.getContext();String type=n.optString("type","slot");View v;if("text".equals(type)||"action".equals(type)){TextView t=new TextView(c);t.setText(n.optString("text",""));t.setTextColor(n.optInt("textColor",Color.WHITE));v=t;}else if("spacer".equals(type)){v=new Space(c);}else{v=new FrameLayout(c);}v.setTag(n.optString("id"));((ViewGroup)parent).addView(v,new ViewGroup.LayoutParams(-1,"spacer".equals(type)?1:-2));return v;}
    private static void applyProperties(View v,JSONObject n){String visibility=n.optString("visibility","");if("visible".equals(visibility))v.setVisibility(View.VISIBLE);else if("gone".equals(visibility))v.setVisibility(View.GONE);else if("invisible".equals(visibility))v.setVisibility(View.INVISIBLE);if(n.has("text")&&v instanceof TextView)((TextView)v).setText(n.optString("text",""));if(n.has("textSize")&&v instanceof TextView){float x=(float)n.optDouble("textSize",-1);if(x>=8&&x<=48)((TextView)v).setTextSize(x);}if(n.has("textColor")&&v instanceof TextView)((TextView)v).setTextColor(n.optInt("textColor",Color.WHITE));if(n.has("padding")){int p=n.optInt("padding",-1);if(p>=0&&p<=128)v.setPadding(p,p,p,p);}ViewGroup.LayoutParams lp=v.getLayoutParams();if(lp instanceof ViewGroup.MarginLayoutParams){int m=n.optInt("margin",-1);if(m>=0&&m<=128){ViewGroup.MarginLayoutParams x=(ViewGroup.MarginLayoutParams)lp;x.leftMargin=x.topMargin=x.rightMargin=x.bottomMargin=m;v.setLayoutParams(x);}}if(n.has("weight")&&lp instanceof android.widget.LinearLayout.LayoutParams){float w=(float)n.optDouble("weight",-1);if(w>=0&&w<=20){((android.widget.LinearLayout.LayoutParams)lp).weight=w;v.setLayoutParams(lp);}}}
    public static JSONObject applyOperations(JSONObject document,JSONArray operations){try{JSONObject out=new JSONObject(document.toString());JSONArray nodes=out.optJSONArray("nodes");if(nodes==null){nodes=new JSONArray();out.put("nodes",nodes);}if(operations==null||operations.length()>MAX_OPS)throw new IllegalArgumentException("operations limited to 80");for(int i=0;i<operations.length();i++){JSONObject op=operations.optJSONObject(i);if(op==null)throw new IllegalArgumentException("operation must be object");String action=op.optString("action",op.optString("op","set"));String id=op.optString("id","");if(!safeId(id))throw new IllegalArgumentException("invalid stable id");int at=index(nodes,id);if("add".equals(action)){if(at>=0)throw new IllegalArgumentException("node already exists");JSONObject n=new JSONObject(op.toString());n.remove("action");n.remove("op");nodes.put(n);}else if("remove".equals(action)){if(at>=0)nodes.optJSONObject(at).put("removed",true);}else if("move".equals(action)||"reparent".equals(action)){if(at<0){JSONObject n=new JSONObject().put("id",id).put("type",op.optString("type","slot"));nodes.put(n);at=nodes.length()-1;}JSONObject n=nodes.optJSONObject(at);if("move".equals(action))n.put("index",Math.max(0,Math.min(399,op.optInt("index",0))));else n.put("parent",op.optString("parent",""));}else if("set".equals(action)){if(at<0){JSONObject n=new JSONObject(op.toString());n.remove("action");n.remove("op");nodes.put(n);at=nodes.length()-1;}JSONObject n=nodes.optJSONObject(at);for(String k:new String[]{"parent","visibility","text","textSize","textColor","padding","margin","weight","index","removed","type"})if(op.has(k))n.put(k,op.get(k));}else throw new IllegalArgumentException("unsupported canvas action");}return out;}catch(IllegalArgumentException e){throw e;}catch(Exception e){throw new IllegalArgumentException("invalid canvas operation",e);}}
    private static int index(JSONArray a,String id){for(int i=0;i<a.length();i++)if(id.equals(a.optJSONObject(i).optString("id")))return i;return -1;}
    private static boolean safeId(String id){return id!=null&&!id.trim().isEmpty()&&id.length()<=64&&id.indexOf('/')<0&&id.indexOf('\\')<0&&!id.matches(".*[\\p{Cntrl}].*")&&!"root".equals(id);}
    private static View find(View v,String id){if(id.equals(v.getTag()))return v;if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++){View r=find(g.getChildAt(i),id);if(r!=null)return r;}}return null;}
}
